### ISSUE TITLE
How to find the VQAD model size correctly

### ISSUE THREAD

**Issue by cv-dote** [NVIDIAGameWorks/kaolin-wisp#57]
Thanks for this great work!
I am trying to reproduce the VQAD paper results.  
I train the VQAD model using the RTMV datasets with default config.  
But the model size is over 20MB, not small as the paper.  
Could you please show me how to calculate the correct model size?

training config
```
global:
  exp_name: "test-vqad-nerf"

optimizer:
  optimizer_type: "rmsprop"
  lr: 0.001

dataset:
  dataset_type: "multiview"
  num_rays_sampled_per_img: 4096
  multiview_dataset_format: "rtmv"
  mip: 2
  bg_color: "white"

renderer:
  tracer_type: "PackedRFTracer"
  num_steps: 16
  render_batch: 4000
  camera_origin:
    - -3.0
    - 0.65
    - -3.0
  shading_mode: "rb"
  render_res:
    - 1024
    - 1024

trainer:
  trainer_type: "MultiviewTrainer"
  epochs: 50
  batch_size: 1
  model_format: "full"
  valid_every: 50
  save_every: 50
  render_every: 50

grid:
  grid_type: "CodebookOctreeGrid"
  interpolation_type: "linear"
  multiscale_type: "sum"
  feature_dim: 5
  feature_std: 0.01
  base_lod: 5
  num_lods: 4
  codebook_bitwidth: 4

net:
  nef_type: "NeuralRadianceField"
  hidden_dim: 128
  num_layers: 1
  out_dim: 4

embedder:
  embedder_type: "positional"

```

the script I used to calculate the model size
```
import torch

model = torch.load("path/to/model")
param_size = 0

for param in model.parameters():
    param_size += param.nelement() * param.element_size()
buffer_size = 0
for buffer in model.buffers():
    buffer_size += buffer.nelement() * buffer.element_size()

size_all_mb = (param_size + buffer_size) / 1024**2
print('model size: {:.3f}MB'.format(size_all_mb))
```

Thanks in advance!
