### ISSUE TITLE
Devcontainer

### ISSUE THREAD

**Issue by nkyriazis** [NVIDIAGameWorks/kaolin-wisp#61]
It's very useful to have the docker images, especially for development. It's great to quickly jump in the container and develop. However, since wisp [comes bundled](https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/8df9d034224da45053bf135a2e9a640edf23d084/tools/linux/Dockerfile#L10), it's hard to develop from within the container.

Is there an idiomatic way of incorporating dynamic changes to the original wisp python code while in the container, in a persistent fashion that does not involve rebuilding the container? E.g., have the python part of wisp being mounted as a volume.

**Comment by nkyriazis** [comment]
@Caenorst thanks for taking the time to answer.

I was going for something less hacky than the following.

**docker-compose.yml**:
```yaml
version: '3.9'

services:
  # Make sure to have followed the instructions in
  # INSTALL.md and arrive at an image with the tag `wisp`
  app:
    image: wisp
    runtime: nvidia
    environment:
      DISPLAY: ${DISPLAY}
      # make sure mounted wisp is found before builtin wisp
      PYTHONPATH: /workspace
    volumes:
      # mount wisp root as workspace
      - .:/workspace
```

It is important to set the PYTHONPATH to have a top priority of mounted wisp (against bundled wisp). Even so, the _C.so needs to be copied over to the mounted wisp from the bundled and built wisp.
